spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 508888
    url: jdbc:mysql://localhost:3307/spring?serverTimezone=Asia/Shanghai
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: "deleted"
      logic-not-delete-value: 0
      logic-delete-value: 1
